# Alt küme Üzerinde İslem Yapmak

In [2]:
import numpy as np

In [3]:
a = np.random.randint(10, size = (5,5))
a

array([[6, 1, 0, 0, 5],
       [7, 3, 9, 5, 1],
       [6, 8, 9, 8, 4],
       [2, 5, 5, 5, 3],
       [3, 5, 6, 4, 3]])

In [4]:
alt_a = a[0:3,0:2]
alt_a

array([[6, 1],
       [7, 3],
       [6, 8]])

In [5]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888

In [6]:
alt_a

array([[9999,    1],
       [   7, 8888],
       [   6,    8]])

In [8]:
a #alt kumede yaptigimiz degisiklik ana kumeye de etki etmis onu goruyoruz

array([[9999,    1,    0,    0,    5],
       [   7, 8888,    9,    5,    1],
       [   6,    8,    9,    8,    4],
       [   2,    5,    5,    5,    3],
       [   3,    5,    6,    4,    3]])

In [9]:
m = np.random.randint(10, size = (5,5))
m

array([[5, 8, 7, 9, 8],
       [8, 0, 6, 5, 3],
       [9, 3, 8, 5, 3],
       [6, 8, 0, 7, 7],
       [7, 7, 7, 3, 9]])

In [16]:
alt_m = m[0:3, 0:2].copy() #copy ile yaparsak ana kumeden bagimsizlasir

In [17]:
alt_m

array([[5, 8],
       [8, 0],
       [9, 3]])

In [18]:
alt_m[0,0] = 9999
alt_m[1,1] = 8888

In [19]:
alt_m

array([[9999,    8],
       [   8, 8888],
       [   9,    3]])

In [20]:
m

array([[5, 8, 7, 9, 8],
       [8, 0, 6, 5, 3],
       [9, 3, 8, 5, 3],
       [6, 8, 0, 7, 7],
       [7, 7, 7, 3, 9]])