# Slicing ile Elemanlara Erişmek (Array alt kümelerine Erişmek)

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[0::2]

array([20, 22, 24, 26, 28])

In [7]:
a[1::2]

array([21, 23, 25, 27, 29])

In [8]:
a[0::3]

array([20, 23, 26, 29])

## İki boyutlu arraylerde slice islemleri

In [9]:
m = np.random.randint(10, size=(5,5))

In [10]:
m

array([[3, 5, 8, 5, 4],
       [4, 7, 3, 6, 0],
       [4, 6, 2, 5, 4],
       [4, 9, 8, 7, 9],
       [3, 0, 6, 5, 4]])

In [11]:
m[:,0]

array([3, 4, 4, 4, 3])

In [12]:
m[:,1]

array([5, 7, 6, 9, 0])

In [13]:
m[:,4]

array([4, 0, 4, 9, 4])

In [14]:
m[0,:]

array([3, 5, 8, 5, 4])

In [15]:
m[0]

array([3, 5, 8, 5, 4])

In [17]:
m[1,:]

array([4, 7, 3, 6, 0])

In [18]:
m

array([[3, 5, 8, 5, 4],
       [4, 7, 3, 6, 0],
       [4, 6, 2, 5, 4],
       [4, 9, 8, 7, 9],
       [3, 0, 6, 5, 4]])

In [19]:
m[0:2, 0:3]

array([[3, 5, 8],
       [4, 7, 3]])

In [20]:
m[::,:2]

array([[3, 5],
       [4, 7],
       [4, 6],
       [4, 9],
       [3, 0]])

In [21]:
m[1:4,3:]

array([[6, 0],
       [5, 4],
       [7, 9]])