# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([5,7,2,3,4,9,2,1,8])

In [3]:
v

array([5, 7, 2, 3, 4, 9, 2, 1, 8])

In [8]:
np.sort(v) #np ile sagrildiginda orjinal yapiyi bozmadi

array([1, 2, 2, 3, 4, 5, 7, 8, 9])

In [7]:
v.sort() #Bu sekilde yapilinca orjinal yapiyi bozdu

In [6]:
v

array([1, 2, 2, 3, 4, 5, 7, 8, 9])

## İki boyutlu arraylerde sıralama işlemi

In [10]:
m = np.random.normal(20,5,(3,3))

In [12]:
m

array([[23.41937516, 28.46724451, 19.19852065],
       [21.17895364, 18.67878083, 19.27847799],
       [32.73012481, 22.5495746 , 26.73589219]])

In [16]:
np.sort(m, axis = 1) #Satirlara göre siralama

array([[19.19852065, 23.41937516, 28.46724451],
       [18.67878083, 19.27847799, 21.17895364],
       [22.5495746 , 26.73589219, 32.73012481]])

In [15]:
np.sort(m, axis = 0) # Sutunlara göre siralama

array([[21.17895364, 18.67878083, 19.19852065],
       [23.41937516, 22.5495746 , 19.27847799],
       [32.73012481, 28.46724451, 26.73589219]])