# Index ile Elemanlara Erişmek

In [2]:
import numpy as np
a = np.random.randint(10, size=10)
a

array([3, 3, 8, 8, 3, 2, 9, 9, 8, 2])

In [3]:
a[3]

8

In [4]:
a[-1]

2

In [5]:
a[0] = 100

In [6]:
a

array([100,   3,   8,   8,   3,   2,   9,   9,   8,   2])

## 2 Boyutlu Arraylerde Index ile Elemanlara Erişmek

In [7]:
m = np.random.randint(10, size= (3,5))
m

array([[8, 5, 1, 1, 3],
       [8, 4, 0, 4, 1],
       [8, 0, 2, 5, 2]])

In [9]:
m[2,3]

5

In [10]:
m[1,4] = 999

In [11]:
m

array([[  8,   5,   1,   1,   3],
       [  8,   4,   0,   4, 999],
       [  8,   0,   2,   5,   2]])

In [14]:
m[0,0] = 1.9

In [15]:
m

array([[  1,   5,   1,   1,   3],
       [  8,   4,   0,   4, 999],
       [  8,   0,   2,   5,   2]])