# Matematiksel İşlemler

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5])

In [3]:
v

array([1, 2, 3, 4, 5])

In [4]:
v - 1

array([0, 1, 2, 3, 4])

In [10]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [5]:
v + 3

array([4, 5, 6, 7, 8])

In [11]:
np.add(v,3)

array([4, 5, 6, 7, 8])

In [6]:
v * 5

array([ 5, 10, 15, 20, 25])

In [12]:
np.multiply(v,5)

array([ 5, 10, 15, 20, 25])

In [14]:
v/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [16]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [17]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [18]:
np.power(v,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [19]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [20]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [21]:
v*6/2

array([ 3.,  6.,  9., 12., 15.])

In [22]:
np.divide(np.multiply(v,6),2)

array([ 3.,  6.,  9., 12., 15.])

In [24]:
np.absolute(np.array([-3])) #mutlak deger alma

array([3])

In [25]:
np.sin(360)

0.9589157234143065

In [26]:
np.cos(180)

-0.5984600690578581

In [27]:
a = np.array([1,2,3])

In [28]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [29]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [30]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [32]:
#cheatsheet kopya kagidi anlamina gelir googleda python matematik islemleri cheatsheet yazarsak ulasiriz

# İstatistiksel Hesaplamalar

* np.mean(arr,axis=0) | Returns mean along specific axis
* arr.sum() | Returns sum of arr
* arr.min() | Returns minimum value of arr
* arr.max(axis=0) | Returns maximum value of specific axis
* np.var(arr) | Returns the variance of array
* np.std(arr,axis=1) | Returns the standard deviation of specific axis
* arr.corrcoef() | Returns correlation coefficient of array

In [33]:
v

array([1, 2, 3, 4, 5])

In [36]:
np.mean(v,axis=0)

3.0

In [38]:
v.sum()

15

In [39]:
v.min()

1

In [40]:
v.max(axis=0)

5

In [41]:
np.var(v)

2.0

In [44]:
#Bu istatistiksel bilgileri googledan cheatsheet ile bulup denedim