# Numpy Array'i Oluşturmak

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14,5.9,5,6,8,9])

array([3.14, 5.9 , 5.  , 6.  , 8.  , 9.  ])

In [8]:
np.array([3.14,5.9,5,6,8,9], dtype = "int")

array([3, 5, 5, 6, 8, 9])

**Sifirdan array olusturma**

In [11]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [15]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10,4,(3,4))

array([[ 9.01148687, 12.76412876,  9.56781072, 12.2877581 ],
       [ 9.27187218, 10.1057649 , 14.26408294, 10.56070402],
       [17.30060549,  9.67639709,  1.68719906,  1.18397222]])

In [18]:
np.random.randint(0,10,(3,3))

array([[0, 9, 9],
       [3, 5, 3],
       [9, 6, 6]])