# Numpy ile İki Bilinmeyenli Denklem Çözümü

In [1]:
import numpy as np

* **5*x0+x1=12**
* **x0+3*x1=10**

In [2]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [3]:
a

array([[5, 1],
       [1, 3]])

In [4]:
b

array([12, 10])

In [6]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])